### PR TITLE
Add view for retrieving registrations

### PR DESCRIPTION
**Pull request by KaitCrawford**
Add an API endpoint for retrieving registrations. Requirements:
Allows filtering by fields, especially mother_id (@imsickofmaps I presume this is the uuid that we can expect casepro to have?).
Returns details of related objects

### CODE REVIEW

**Comment by imsickofmaps** [comment]
@KaitCrawford no related objects required I think. But please add filters for `stage, validated, source, created_at` to improve its reusability. Also, some tests would be nice?

**Comment by KaitCrawford** [comment]
@imsickofmaps ready for re-review

**Comment by KaitCrawford** [comment]
cc @miltontony @hodgestar

**Comment by imsickofmaps** [comment]
👍

**Pull request merged**
